#!/usr/bin/env python3
"""
Resolve KML stems (as pasted from filenames without .kml) to location_id via operations.crop_indices.

Writes:
  second_phase_locations.txt       — one line per input (location_id or # UNRESOLVED: …)
  second_phase_locations_report.tsv — stem, matched file_name or NOT_FOUND, location_id

Run from repo root: python scripts/resolve_second_phase_location_ids.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_root))

try:
    from dotenv import load_dotenv

    load_dotenv(_root / ".env")
except ImportError:
    pass

RAW = r"""
FATTEPUR ANNAPPA BYALADAHALLI USRH24 THIPPANNA
FATTEPUR SHILPA SUNAGAR USRH24 NAGAPPA
FATTEPUR MANJAPPA K JAJUR USRH24 KARIBASAPPA
FATTEPUR RUDRAPPA JAJURI USRH24 GOVINDAPPA
FATTEPUR MANJUNATHA T CHITTANNANAVAR USRH24 TIPPANNA
FATTEPUR KARABASAPPA G GOPALAPUR USRH24 GANESHA
FATTEPUR NAGARAJ PARASANNANAVAR USRH24 LAXMAPPA
FATTEPUR IRAPPA C USRH24 SHIVAPPA
FATTEPUR M K CHITTANNANAVAR USRH24 KARIBASAPPA
FATTEPUR KARIYAPPA K CHITTANN USRH24 KARIBASAPPA
FATTEPUR YASHODA N PARASANNANAVAR USRH24 NAGARAJ
FATTEPUR RAKESHA HANUMANTAPPA CHITTANNANAVAR USRH24 HANUMANTAPPA
FATTEPUR HANUMANTHAPPA S CHITTANNANAVAR USRH24 SHIVARUDRAPPA
FATTEPUR KARABASAPPA PARASANNANAVAR USRH24 ARJUNAPPA
KUSAGATTI RAMANAGOUDA PATIL USRH24 DODDANINGANAGOUDA
KOTIHAL SHIVANGOUDA PAKKIRGOUD HARIAHAR USRH24 PAKKIRAGOUD
UKKADAGATRI RAJASHEKARAYYA M N USRH24 NAGARAJAYYA
BELUR MANJAPPA HALAPPA BHOOVI USRH24 HALAPPA
BELUR SAVITRAMMA RAJAPPA DODDAMANI USRH24 RAJAPPA
BELUR SHIVARAJ SIDDAPPA KAYTHAPPANVAR USRH24 SIDDAPPA
SOMALAPUR HANUMANTAPPA KANNAPPA GIRIYAMMANAVAR USRH24 KANNAPPA
SOMALAPUR SHEKHAPPA MALLAPPA BATAPPANAVAR USRH24 MALLAPPA
SOMALAPUR CHANDRAPPA IRAPPA KOTIHAL USRH24 IRAPPA
SOMALAPUR NINGAPPA KANNAPPA GIRIYAMMANAVAR USRH24 KANNAPPA
SOMALAPUR RAJAPPA BATAPPANAVAR USRH24 MALLAPPA
SOMALAPUR SHIVAPPA BATAPPANAVAR USRH24 MALLAPPA
SOMALAPUR PARAMESHAPPA MALLAPPA GOUDAR USRH24 MALLAPPA
SOMALAPUR RENUKA CHNDRAPPA BATHAPPANAVAR USRH24 CHANDRAPPA
SOMALAPUR PUSPA KANNAPPA BATHAPPANAVAR USRH24 KANNAPPA
SOMALAPUR RAJAPPA SIDDAPPA VANROTTI USRH24 SIDDAPPA
SOMALAPUR HANUMANTAPPA KANNAPPA BATHAPPANAVAR USRH24 KANNAPPA
HEELADAHALLI PARASAPPA KARIYAPPA KILRAD USRH24 KARIYAPPA
HEELADAHALLI JAGADISH KALLAPPA MALABER USRH24 KALLAPPA
KONANA TAMBAGI HOLIBASAPPA DILLEPPA VAGGAPPANAVAR USRH24 DILLEPPA
KONANA TAMBAGI HOLIYAPPA NINGAPPA BARKI USRH24 NINGAPPA
KONANA TAMBAGI KOTRESHA N BARKI USRH24 NINGAPPA
KONANA TAMBAGI NEELAVVA HANUMNTAPPA RAVALLER USRH24 HANUMANTAPPA
KONANA TAMBAGI JEENATH BNU USRH24 MARUFF SAB
BADAHALUPADA ANIL DAS USRH24 GOLAKHA DAS
BADAHALUPADA ARJUN DAS USRH24 NITYANAND DAS
BADAHALUPADA DHIRENDRA DAS  USRH24 BUJI DAS 
BADAHALUPADA KAVITA DAS USRH24 SURYAKANATA DAS
BADAHALUPADA LAXMIDHAR DAS  USRH24 VISHNU DAS 
BADAHALUPADA MINA MALIK USRH24 DAIN MALIK
BADAHALUPADA MINAKSHI DAS  USRH24 ADHIKARI DAS 
BADAHALUPADA PURNIAMA MALIK  USRH24 DILIP KUMAR MALIK 
BADAHALUPADA RANJULATA MALLIK USRH24 SATRUGHAN MALIK
BADAHALUPADA SANATAN DAS USRH24 BIDRA DAS
BADAHALUPADA SASHIKANT DAS  USRH24 VISHNU DAS 
BADAHALUPADA SATRUGHAN MALIK USRH24 DAMA MALIK
BADAHALUPADA TILOTTAMA DAS USRH24 TAULI MALIK
BAHARBILA NANDKISHORE DALI USRH24 DALA  DALI
BAHARBILA PRASANTA BEHERA USRH24 FAKIR MOHAN BEHERA
BETALIGAON DHIRENDRA PRADHAN USRH24 KALANDI PRADHAN
KALIDASHPUR BISWANATH SETHI USRH24 RAMESH SETHI
KALIDASHPUR SADANANDA BEHARA USRH24 RATHA BEHERA
KALIDASHPUR -1 ABHIMANYU BEHERA USRH24 SAMBU BEHERA
KALIDASHPUR -1 BASANTA PALEI USRH24 MANGARAJ PALAI
KALIDASHPUR -1 GOPAL BEHARA USRH24 AGANI BEHERA
KALIDASHPUR -1 JADUNATH BEHERA USRH24 SAMBU BEHERA
KALIDASHPUR -1 LAXMAN BEHAR USRH24 AINTHI BEHARA
KALIDASHPUR -1 NARAHARI BARIK USRH24 TIMA BARIK
KALIDASHPUR -1 NARAYAN CHANDRA BEHERA USRH24 SIRAEI BEHERA
KALIDASHPUR -1 NIRANJAN PALEI USRH24 NRUSINGH PALAI
KALIDASHPUR -1 PRAFULLA BEHERA USRH24 GOLAK BEHARA
KALIDASHPUR -1 SANKARSAN NAYAK USRH24 NARAYAN NAYAK
KULASAHI BIDYA DHAR SAHOO USRH24 BICHITRA KUMAR SAHOO
NIZAMPUR MANORAMA PARIDA USRH24 SRIDHAR NAYAK
RADOGAON BISHWA RANJAN BISWAL USRH24 BAISHNAB BISWAL
RADOGAON SIMA RANI BISWAL USRH24 SHARAT CHANDRA BISWAL
SANAHALUPADA DEBASIS NAYAK USRH24 PURANCHANDA NAYAK
SANAHALUPADA USHARANI NAYAK USRH24 PURANCHANDA NAYAK
SOLAPAT RABI NARAYAN BISWAL USRH24 RANJAN KUMAR BISWAL
TALARADAGAN JITENDRA KUMAR BEHERA USRH24 PRATAP KUMAR BEHERA
TALARADAGAN PRATAP KUMAR BEHERA USRH24 BISWANATH BEHERA
TALARADAGAN PUSPASINI DAS USRH24 JITENDRA KUMAR BEHERA
TOTASAHI NAROTTAM KAR USRH24 NRUSINGHA CHANDRA KAR
KURUTHIA BIMALA PARIDA USRH24 ANIL PARIDA
KURUTHIA DHRUBA CHANDRA DAS USRH24 SHYAMSUNDAR DAS
KURUTHIA GOURAHARI PARIDA USRH24 MAHESWAR PARIDA
KURUTHIA HADIA MURMU USRH24 JANJALI MURMU
KURUTHIA HEMANTA DAS. USRH24 ABADUTT DAS
KURUTHIA KAJAL KUNDU USRH24 NIRANJAN KUNDU
KURUTHIA NANDANA JENA USRH24 SANYASI JENA
KURUTHIA NIGAMANANDA DAS USRH24 RADHASHYAM DAS
KURUTHIA NIRANJAN KUNDU. USRH24 RAKHAL CHANDRA KUNDU
KURUTHIA PUSPANJALI PARIDA USRH24 MAGUNI KAMILA
KURUTHIA RABINDRA HANSDA USRH24 GALU HANSDA
KURUTHIA RADHAGOBINDA BEHERA USRH24 BIRENDRA BEHERA
KURUTHIA RAJANI KANTA PRADHAN USRH24 SHYAM SUNDAR PRADHAN
KURUTHIA RAMCHANDRA SINGH USRH24 BAIKUNTHA SINGH
KUSUDA NIGAMANANDA DAS USRH24 RADHASHYAM DAS
NAHARA CHHABI SETHI USRH24 RAGHUNATH SETHI
NAHARA RAGHUNATH SETHI USRH24 KHETRA MOHAN SETHI
SAHAPUR BIJAYA SEN USRH24 PRIYABRATA
SAHAPUR BIKASH CHANDRA HUI USRH24 MRUTYANJAN HUI
SAHAPUR CHINMAY KUMAR HUI USRH24 BIKASH CHANDRA HUI
SAHAPUR CHITARANJAN HUI USRH24 SAROJ HUI
SAHAPUR CHITTARANJAN DAS USRH24 SHASHADHARA DAS
SAHAPUR DEBABRATA SEN USRH24 SANTOSH SEN
SAHAPUR GANDHARI SEN USRH24 SATYABRATA KUNDU
SAHAPUR HARISHANKAR DAS USRH24 SHASASHAR DAS
SAHAPUR JAYANTA KUMAR SETHI USRH24 BIMAL CHANDRA SETHI
SAHAPUR MITHUN KUMAR JENA USRH24 RANJAN KUMMAR JENA
SAHAPUR NIRMAL JENA USRH24 DEBENDRA JENA
SAHAPUR PRIYABRATA SEN USRH24 SANTOSH SEN
SAHAPUR PURENDU CHAUHAN USRH24 BIPIN CHANDRA CHAUHAN
SAHAPUR RATAN KUMAR DUTTA USRH24 SUBASH KUMAR DUTTA
SAHAPUR SANJULATA SEN USRH24 DEBABRATA SEN
SAHAPUR SANTOSH KUMAR HUI USRH24 KALI HUI
SAHAPUR SATYBRATA SEN USRH24 SANTOSH KUMAR SEN
SAHAPUR SUBODH DUTTA USRH24 HEMCHAND DUTTA
SAHAPUR TRUPTI HUI USRH24 CHITRANJAN HUI
SANTIA AJAY ANDIA USRH24 ABHIMANYU ANDIA
SANTIA AMULYA KUMAR ANDIA USRH24 KANHU CHARAN ANDIA
SANTIA AMULYA SAHU USRH24 HARADHAN SAHU
SANTIA BHAGIRATH ANDIA USRH24 KANHU CHARAN ANDIA
SANTIA HAREKRUSHNA ANDAI USRH24 JUDHISTHIR ANDIA
SANTIA JITENDRA RANA USRH24 NITYA GOPAL RANA
SANTIA LASA MURMU USRH24 BHIMA MURMU
SANTIA MALATI HEMBRAM USRH24 KHELA MURMU
SANTIA SANDHYA RANI ANDIA USRH24 AMULYA KUMAR ANDIA
SANTIA SANTILATA NAG USRH24 ASWINI KUMAR NAG
SANTIA SHIBANANDA RANA USRH24 HARISHCHANDRA RANA
SANTIA TRUSHNA RANI PARIDA USRH24 RANJIT KUMAR PARIDA
SANTIA UTTAM DAS USRH24 BANESWAR DAS
BALARAMPUR BASANTI GIRI USRH24 RAMCHANDRA GIRI
BALARAMPUR BHAGIRATHA DHAL USRH24 GOBINDA DHAL
BALARAMPUR BIJAY MUKHI USRH24 KASHI MUKHI
BALARAMPUR HARENDRA MUKHI USRH24 SANYASI MUKHI
BALARAMPUR KAMAL LOCHAN MUKHI USRH24 BHABENDRA MUKHI
BALARAMPUR LAXMIDHAR BADU USRH24 MADHUSUDAN BADU
BALARAMPUR PRIYABANSHI DAS USRH24 DHIRENDRA KUMAR DAS
BALARAMPUR SANJAY KUMAR BADU USRH24 MADHUSUDAN BADU
BALARAMPUR SURESH BIJULI USRH24 SHIV BIJULI
DANDIKA GANESWAR RANGA USRH24 PRASANA RANGA
KATISAHI AJAY KUMAR BEHERA USRH24 TRILOCHAN BEHERA
KATISAHI ANANT KUMAR BEHERA USRH24 ANADI CHARAN BEHERA
KATISAHI ANJANA BHUYAN USRH24 GOUTTAM KUMAR BHUYAN
KATISAHI BANALATA PADHIARI USRH24 NITYANANDA GIRI
KATISAHI BHAKTABALA KAR USRH24 NITYANANDA KAR
KATISAHI BINOD BEHERA USRH24 MADAN BEHERA
KATISAHI CHABIRANI JENA USRH24 NARAYAN DAS
KATISAHI CHANDAN KUMAR PRADHAN USRH24 SATRUGHNA PRADHAN
KATISAHI CHHANU BESHRA USRH24 NACHHU BESAR
KATISAHI DAMAYANTI BHUYAN USRH24 HAREKRUSHNA MANDAL
KATISAHI DEBENDRA BEHERA USRH24 KALICHARAN BEHERA
KATISAHI DEEPAK KUMAR JENA USRH24 DIANBANDHU JENA
KATISAHI GOPALKRUSHNA  DAS ADHIKARI USRH24 HRUDANAND DAS ADHIKARI
KATISAHI GOUTTAM KUMAR BHUYAN USRH24 RANJAN KUMAR BHUYAN
KATISAHI HARIHAR PRADHAN USRH24 CHAKRADHAR PRADHAN
KATISAHI JYOTIRMAY BHUYAN USRH24 SUBAS KUMAR BHUYAN
KATISAHI KABITA BEHERA USRH24 PARSURAM BEHERA
KATISAHI KHAGENDRA JENA USRH24 ARJUN JENA
KATISAHI MAHESWAR PRADHAN USRH24 GADADHAR PRADHAN
KATISAHI MANORANJAN BHUYAN USRH24 BHAGBAN BHUYAN
KATISAHI NAROTTAM JENA USRH24 CHAKRADHAR JENA
KATISAHI PARSHURAM DAS USRH24 DINABANDHU DAS
KATISAHI PRADIP KUMAR BHUYAN USRH24 BHAGBAN BHUYAN
KATISAHI PRASANTA BEHERA USRH24 UPENDRA BEHERA
KATISAHI SANJAY KUMAR DAS USRH24 SRIMANTA DAS
KATISAHI SHANKARSAN DAS USRH24 BHUPENDRA DAS
KATISAHI SUDARSHAN BEHERA USRH24 RABINDRA BEHERA
KATISAHI SURENDRA BEHERA USRH24 MADAN BEHERA
KATISAHI UTTAM MARENDI USRH24 SURENDRA MARNDI
TIGIRIA AJIT KUMAR DAS USRH24 SHANKARSHAN DAS
TIGIRIA ANJULATA JENA USRH24 AJAY JENA
TIGIRIA DAMODAR JENA USRH24 PURNACHANDRA JENA
TIGIRIA KAMALAKANTA MAHALIK USRH24 GANESHWAR MAHALIK
TIGIRIA MANIKA JENA USRH24 BANSHIDHAR JENA
TIGIRIA PRASHANTA KUMAR DAS USRH24 ACHYUTA DAS
TIGIRIA PRATAP JENA USRH24 PURNACHANDRA JENA
TIGIRIA RADHASHYAM MAHALIK USRH24 GOBINDA MAHALIK
TIGIRIA SASHIKANTA JENA USRH24 BARENDRA JENA
TIGIRIA SIBANANDA JENA USRH24 
TIGIRIA SRIKANTA DAS USRH24 ACHYUTANANDA DAS
TIGIRIA SRIKANTA JENA USRH24 BARENDRA JENA
"""


def canon_key(s: str) -> str:
    t = " ".join(s.split())
    t = t.strip().rstrip(".")
    t = re.sub(r"\.kml$", "", t, flags=re.I)
    return t.lower()


def build_index(session) -> dict[str, tuple[str, str]]:
    """normalized_file_stem -> (location_id, file_name)"""
    from sqlalchemy import text

    rows = session.execute(
        text(
            """
            SELECT DISTINCT ON (lower(regexp_replace(trim(file_name), '\\.kml$', '', 'i')))
                lower(regexp_replace(trim(file_name), '\\.kml$', '', 'i')) AS k,
                location_id::text,
                trim(file_name) AS file_name
            FROM operations.crop_indices
            WHERE file_name IS NOT NULL AND trim(file_name) <> ''
            ORDER BY k, id DESC
            """
        )
    ).fetchall()
    out: dict[str, tuple[str, str]] = {}
    for r in rows:
        if not r or not r[0]:
            continue
        k, lid, fn = str(r[0]), str(r[1]).strip(), str(r[2]).strip()
        out[k] = (lid, fn)
    return out


def main() -> int:
    from core.db import SessionLocal

    stems = [ln.strip() for ln in RAW.strip().splitlines() if ln.strip()]
    session = SessionLocal()
    try:
        idx = build_index(session)
    finally:
        session.close()

    out_lines: list[str] = []
    report: list[str] = []
    missing = 0
    for stem in stems:
        k = canon_key(stem)
        alt_keys = [k]
        if "bishwanath" in k:
            alt_keys.append(k.replace("bishwanath", "biswanath"))
        if "biswanath" in k:
            alt_keys.append(k.replace("biswanath", "bishwanath"))
        if "radoogaon" in k:
            alt_keys.append(k.replace("radoogaon", "radogaon"))
        if "radogaon" in k:
            alt_keys.append(k.replace("radogaon", "radoogaon"))

        hit = None
        for ak in alt_keys:
            if ak in idx:
                hit = idx[ak]
                break
        if hit:
            lid, fn = hit
            out_lines.append(lid)
            report.append(f"{stem}\t{fn}\t{lid}")
        else:
            missing += 1
            out_lines.append(f"# UNRESOLVED: {stem}")
            report.append(f"{stem}\tNOT_FOUND\t")

    out_path = _root / "second_phase_locations.txt"
    rep_path = _root / "second_phase_locations_report.tsv"
    out_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    rep_path.write_text("input_stem\tmatched_file_name\tlocation_id\n" + "\n".join(report) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(stems)} lines, {missing} unresolved)")
    print(f"Wrote {rep_path}")
    return 0 if missing == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
