-- Align operations.crop_indices with latest production pipeline/output.
-- Safe migration: only IF EXISTS / IF NOT EXISTS operations.

BEGIN;

ALTER TABLE IF EXISTS operations.crop_indices
    DROP COLUMN IF EXISTS centroid_lat,
    DROP COLUMN IF EXISTS centroid_lon,
    DROP COLUMN IF EXISTS village,
    DROP COLUMN IF EXISTS district,
    DROP COLUMN IF EXISTS state,
    DROP COLUMN IF EXISTS mandal,
    DROP COLUMN IF EXISTS postcode,
    DROP COLUMN IF EXISTS extracted_village;

ALTER TABLE IF EXISTS operations.crop_indices
    ADD COLUMN IF NOT EXISTS blue DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS green DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS red DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS rededge1 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS rededge2 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS rededge3 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS nir DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS narrow_nir DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swir1 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swir2 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ndwi_gao DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS date_start DATE,
    ADD COLUMN IF NOT EXISTS date_end DATE;

COMMIT;

